# Generated by Django 5.1.4 on 2025-04-07 22:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_customer'),
        ('products', '0008_alter_brand_image_name_alter_poductgroup_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ درج سفارس')),
                ('update_date', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش سفارس')),
                ('is_finaly', models.BooleanField(default=True, verbose_name='وضعیت پرداخت')),
                ('oder_code', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='کد تولیدی برای سفارش')),
                ('discount', models.IntegerField(blank=True, default=None, null=True, verbose_name='تخفیف روی فاکتور')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details1', to='orders.order', verbose_name='سفارش')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details2', to='products.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'جزییات سفارش',
                'verbose_name_plural': 'جزییات سفارشات',
            },
        ),
    ]
