# Generated by Django 5.1.4 on 2025-04-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_title', models.CharField(max_length=32, verbose_name='نوع روش پرداخت')),
            ],
            options={
                'verbose_name': 'نوع روش پرداخت',
                'verbose_name_plural': 'نوع روش های پرداخت',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyman_types', to='orders.paymenttype', verbose_name='نوع روش پرداخت'),
        ),
    ]
