# Generated by Django 5.1.4 on 2025-05-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymenttype_order_description_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='Product',
            new_name='product',
        ),
    ]
